In [1]:
import pandas as pd
import pandas_baseline as pb

In [2]:
df = pd.read_csv('./example_phonebook_data.csv')

In [3]:
pb.count_by_email_provider(df=df)

        email_provider  count
0       dummyemail.com     25
1  otherdummyemail.com     25

In [4]:
pb.count_by_state(df=df)

        state  count
0  California     13
1     Florida     12
2    New York     12
3       Texas     13