In [1]:
import os
import dotenv
dotenv.load_dotenv(dotenv_path='.env')

from openai import OpenAI

from dataset import Pokedex
from embeddings import generate_embeddings
from vector_store import VectorStore

In [2]:
client = OpenAI(api_key=os.environ['OPENAI_API_KEY'])

In [3]:
dex = Pokedex()

In [4]:
dex.df.head()

,national_number,english_name,description,primary_type,secondary_type
0,1,Bulbasaur,there is a plant seed on its back right from t...,grass,poison
1,2,Ivysaur,"when the bulb on its back grows large, it appe...",grass,poison
2,3,Venusaur,its plant blooms when it is absorbing solar en...,grass,poison
3,4,Charmander,it has a preference for hot things. when it ra...,fire,NaN
4,5,Charmeleon,"it has a barbaric nature. in battle, it whips ...",fire,NaN

In [5]:
dex.df.iloc[4].description

'it has a barbaric nature. in battle, it whips its fiery tail around and slashes away with sharp claws.'

In [6]:
embeddings = generate_embeddings(texts=dex.df.description.tolist(), oai_client=client)

In [7]:
len(embeddings[0])

1536

In [8]:
vs = VectorStore(dimension=len(embeddings[0]))

In [9]:
vs.add(emb=embeddings, ids=dex.df.national_number.tolist())

In [10]:
query = "legendary fire"

In [11]:
query_emb = generate_embeddings(texts=[query], oai_client=client)[0]

In [12]:
d, i = vs.search(query_embedding=query_emb)

In [13]:
matches = dex.get_indices(i[0])
matches

,national_number,english_name,description,primary_type,secondary_type
642,643,Reshiram,this legendary pokémon can scorch the world wi...,dragon,fire
643,644,Zekrom,this legendary pokémon can scorch the world wi...,dragon,electric
887,888,Zacian,"known as a legendary hero, this pokémon absorb...",fairy,fairy
513,514,Simisear,a flame burns inside its body. it scatters emb...,fire,NaN
156,157,Typhlosion,typhlosion obscures itself behind a shimmering...,fire,NaN
256,257,Blaziken,"in battle, blaziken blows out intense flames f...",fire,fighting
627,628,Braviary,"known for its bravery and pride, this majestic...",normal,flying
145,146,Moltres,it’s one of the legendary bird pokémon. when m...,fire,flying
645,646,Kyurem,this legendary ice pokémon waits for a hero to...,dragon,ice
254,255,Torchic,"torchic sticks with its trainer, following beh...",fire,NaN